version: "3.8"

services:
  localstack:
    profiles: [infra, all]
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    build:
      context: ./local/
      dockerfile: ./localstack.Dockerfile
    ports:
      - "4566:4566"         
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG:-0}
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx

  # we can use amazon RDS and DynamoDB instead of bare postgress and redis
  db:
    profiles: [infra, all]
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - "./local/sql:/docker-entrypoint-initdb.d"
 
  redis:
    profiles: [infra, all]
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  documents-api:
    profiles: [all]
    container_name: documents-api
    image: documents-api
    ports:
      - "80:80"